export const GET_JOURNALS = "GET_JOURNALS"
export const DELETE_JOURNALS = "DELETE_JOURNALS"
export const ADD_JOURNALS = "ADD_JOURNALS"

export const GET_ERRORS = "GET_ERRORS"

export const CREATE_MESSAGES = "CREATE_MESSAGES"


export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"