# Generated by Django 2.2.14 on 2021-07-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='page',
        ),
        migrations.AlterField(
            model_name='paper',
            name='issue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
