# Generated by Django 2.2.14 on 2021-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='conference_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='organised_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
