# Generated by Django 2.2.14 on 2021-06-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='ISSN',
            new_name='issn',
        ),
    ]
