# Generated by Django 2.2.14 on 2021-07-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20210706_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='organised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
