# Generated by Django 2.2.14 on 2021-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20210707_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='co_authors',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='paper',
            name='organised_date',
            field=models.DateField(blank=True, default=models.DateField(blank=True, null=True), null=True),
        ),
    ]
