# Generated by Django 2.2.14 on 2021-07-01 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20210630_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference_article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
