# Generated by Django 2.2.14 on 2021-07-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20210708_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='ISBN',
            new_name='isbn',
        ),
    ]
