# Generated by Django 2.2.14 on 2021-07-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_auto_20210702_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, null=True),
        ),
    ]
